apiVersion: v1
kind: Service
metadata:
  name: position-tracker-svc
spec:
  selector:
    app: position-tracker
  type: NodePort
  ports:
  - name: position-tracker-svc
    port: 80 
    nodePort: 30020