apiVersion: v1
kind: Service
metadata:
  name: queue-svc
spec:
  selector:
    app: queue
  type: NodePort
  ports:
  - name: queue
    port: 8161 
    nodePort: 30010 

  - name: endpoint
    port: 61616