apiVersion: v1
kind: Service
metadata:
  name: queue-svc
spec:
  selector:
    app: queue
  type: NodePort
  ports:
  - name: queue
    port: 8161 
    nodePort: 30010 

  - name: endpoint
    port: 61616

---

apiVersion: v1
kind: Service
metadata:
  name: position-tracker-svc
spec:
  selector:
    app: position-tracker
  type: NodePort
  ports:
  - name: position-tracker-svc
    port: 80 
    nodePort: 30020