apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    app: nginx
spec:
  containers:
  - name: nginx
    image: nginx:1.14.0-alpine
    ports:
    - containerPort:  80
      name: http-nginx-svc